steps:
  - label: "GPU integration with julia v1"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.6"
      - JuliaCI/julia-test#v1: ~
    env:
      JULIA_PKG_SERVER: ""
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60

  - label: "GPU integration with julia v1.7-nightly"
    plugins:
      - JuliaCI/julia#v1:
          version: "1.7-nightly"
      - JuliaCI/julia-test#v1: ~
    env:
      JULIA_PKG_SERVER: ""
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60
